config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  namespace :admins do
    resources :patients
    resources :doctors
    resources :categories
  end

  resources :users
  resources :categories
  resources :appointments
  resources :recommendations

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/views/layouts/shared/_flash_messages.html.erb
<% if flash[:alert].present? %>
  <div class="alert alert-danger mt-2 d-flex justify-content-between" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:notice].present?  %>
  <div class="alert alert-success mt-2  d-flex justify-content-between" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/shared/_sidebar.html.erb
<div class="col-1 col-md-1 col-xl-1 px-sm-1 px-0" style="background: #1ec8c8;">
  <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100 sticky-top">
    <ul class="nav nav-pills flex-column mb-sm-auto mt-5 w-100 align-items-center align-items-sm-start" id="menu">
      <li class="nav-item p-2 rounded mb-2 w-100" style="background: #2d8791;">
        <%= link_to user_path(current_user), class: "nav-link align-middle px-0 text-white text-center" do %>
          <span>Профиль</span>
        <% end %>
      </li>
      <% if current_user.has_role?(:admin) %>
        <li class="nav-item p-2 rounded mb-2 w-100" style="background: #2d8791;">
          <%= link_to admins_patients_path, class: "nav-link align-middle px-0 text-white text-center" do %>
            <span>Пациенты</span>
          <% end %>
        </li>
        <li class="nav-item p-2 rounded  mb-2 w-100" style="background: #2d8791;">
          <%= link_to admins_doctors_path, class: "nav-link align-middle px-0 text-white text-center" do %>
            <span>Доктора</span>
          <% end %>
        </li>
        <li class="nav-item p-2 rounded mb-2 w-100" style="background: #2d8791;">
          <%= link_to admins_categories_path, class: "nav-link align-middle px-0 text-white text-center" do %>
            <span>Категории</span>
          <% end %>
        </li>
      <% end %>
    </ul>
    <hr>
    <div class="pb-4">
      <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" do %>
        <%= bootstrap_icon "box-arrow-left", width: "20px", height: "20px" %>
        <span>Выйти</span>
      <% end %>
    </div>
  </div>
</div>