config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  namespace :admins do
    resources :patients
    resources :doctors
    resources :categories
  end

  resources :users
  resources :categories
  resources :appointments
  resources :recommendations

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_create :assign_default_role

  GENDER = %w[Мужской Женский].freeze

  rolify

  belongs_to :category, optional: true
  has_many :doctor_appointments, class_name: "Appointment", foreign_key: :patient_id, dependent: :destroy
  has_many :patient_appointments, class_name: "Appointment", foreign_key: :doctor_id, dependent: :destroy
  has_many :doctors, through: :doctor_appointments, source: :doctor, dependent: :destroy
  has_many :patients, through: :patient_appointments, source: :patient, dependent: :destroy
  has_many :recommendations, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:phone]

  validates :phone, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  private

  def assign_default_role
    add_role(:patient) if roles.blank?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[update edit]

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = t("user.edit.flash.success")
    else
      flash[:alert] = t("user.edit.flash.alert")
    end

    redirect_to action: :show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone,
                                 :born_date, :gender, :patient_appointments,
                                 :doctor_appointments)
  end
end

app/views/users/edit.html.erb
<% if current_user.has_role? :doctor %>
   <h3 class="mt-3">Редактирование карточки врача</h3>
<% else %>
   <h3 class="mt-3">Редактирование карточки пациента</h3>
<% end %>
<hr>
<div class="ms-5 mx-5">
  <%= form_with model: @user, url: user_path, method: :put do |f| %>
    <div class="field row mb-4">
      <%= f.label "Email", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.email_field :email, 
            autofocus: true,
            autocomplete: "email",
            class: "form-control",
            placeholder: t("devise.form.placeholders.email") %>
      </div>
    </div>
    <div class="field row mb-4">
      <%= f.label "Имя", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :first_name, 
            autofocus: true,
            autocomplete: "first_name",
            class: "form-control",
            placeholder: t("devise.form.placeholders.first_name") %>
      </div>
    </div>
    <div class="field row mb-4">
      <%= f.label "Фамилия", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :last_name, 
            autofocus: true,
            autocomplete: "last_name",
            class: "form-control",
            placeholder: t("devise.form.placeholders.last_name") %>
      </div>
    </div>
    <div class="field row mb-4">
      <%= f.label "Телефон", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.phone_field :phone, 
            autofocus: true,
            autocomplete: "phone",
            class: "form-control",
            placeholder: t("devise.form.placeholders.phone") %>
      </div>
    </div>
    <div class="field row mb-4">
      <%= f.label "Выберите Пол", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.collection_radio_buttons :gender, User::GENDER.map {|k,v| [k,k]}, :first, :last, class: 'col-sm-10' do |button| %>
          <span class="mx-2">
            <%= button.radio_button %>
            <%= button.label %>
          </span>
        <% end %>
      </div>
    </div>
    <div class="field row mb-4">
      <%= f.label "Год рождения", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.date_field :born_date, 
            autofocus: true,
            autocomplete: "born_date",
            class: "form-control",
            placeholder: t("devise.form.placeholders.born_date") %>
      </div>
    </div>
    <hr>
    <div class="d-flex justify-content-end">
      <%= f.submit "Изменить", class: "btn text-white", style: "background: #1ec8c8;" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="d-flex justify-content-between align-items-center">
  <% if current_user.has_role? :doctor %>
    <h3 class="mt-3">Карточка врача</h3>
  <% else %>
    <h3 class="mt-3">Амбулаторная карточка пациента</h3>
  <% end %>
  <%= link_to edit_user_path(current_user), class: "btn mt-3 text-white", style: "background: #1ec8c8;" do %>
    <%= bootstrap_icon "pencil", width: 25, height: 25 %>
  <% end %>
</div>
<hr>
<div>
  <h2 class="mb-4"><%= current_user.first_name %> <%= current_user.last_name %></h2>
  <ul class="list-group list-group-flush">
    <% if current_user.has_role? :doctor %>
      <li class="list-group-item d-flex align-items-center border-0">
        <%= bootstrap_icon "clipboard2-pulse-fill", width: 25, height: 25 %>
        <div class="ms-3">
          <small>Категория</small>
          <p><%= current_user.category.present? ? current_user.category.name : "-" %></p>
        </div>
      </li>
    <% end %>
    <li class="list-group-item d-flex align-items-center border-0">
      <%= bootstrap_icon "person", width: 25, height: 25 %>
      <div class="ms-3">
        <small>Пол</small>
        <p><%= current_user.gender %></p>
      </div>
    </li>
    <li class="list-group-item d-flex align-items-center border-0">
      <%= bootstrap_icon "calendar", width: 25, height: 25 %>
      <div class="ms-3">
        <small>Дата рождения</small>
        <p><%= current_user.born_date.present? ? current_user.born_date.strftime("%F") : "" %></p>
      </div>
    </li>
    <li class="list-group-item d-flex align-items-center border-0">
      <%= bootstrap_icon "phone", width: 25, height: 25 %>
      <div class="ms-3">
        <small>Телефон</small>
        <p><%= current_user.phone %></p>
      </div>
    </li>
    <li class="list-group-item d-flex align-items-center border-0">
      <%= bootstrap_icon "envelope", width: 25, height: 25 %>
      <div class="ms-3">
        <small>Почта</small>
        <p><%= current_user.email %></p>
      </div>
    </li>
  </ul>
</div>
<hr>
<div>
  <% if can? :read, Category %>
    <%= link_to "Записаться к врачу", categories_path, class: "btn text-white", style: "background: #1ec8c8;" %>
  <% end %>
  <% if current_user.has_role? :doctor %>
    <%= link_to "Мои записи #{current_user.patient_appointments.count}", appointments_path, class: "btn text-white mx-3", style: "background: #1ec8c8;" %>
  <% else %>
    <%= link_to "Мои записи #{current_user.doctor_appointments.count}", appointments_path, class: "btn text-white mx-3", style: "background: #1ec8c8;" %>
  <% end %>
</div>