config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  namespace :admins do
    resources :patients
    resources :doctors
    resources :categories
  end

  resources :users
  resources :categories
  resources :appointments
  resources :recommendations

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :users

  validates :name, presence: true, uniqueness: true
end

app/controllers/admins/categories_controller.rb
# frozen_string_literal: true

class Admins::CategoriesController < Admins::AdminController
  before_action :set_category, only: %i[show update edit destroy]

  def index
    @q = Category.ransack(params[:q])
    @q.sorts = "created_at desc" if @q.sorts.empty?
    @pagy, @categories = pagy(@q.result, items: 10)
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = t("categories.create.flash.success")
    else
      flash[:alert] = t("categories.create.flash.alert")
    end

    redirect_to action: :index
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = t("categories.edit.flash.success")
    else
      flash[:alert] = t("categories.edit.flash.alert")
    end

    redirect_to action: :index
  end

  def destroy
    return unless @category.destroy

    flash[:notice] = t("categories.destroy.flash.success")
    redirect_to action: :index
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :users)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @q = Category.ransack(params[:q])
    @categories = @q.result
  end

  def show
    @category = Category.find(params[:id])
    @pagy, @category_doctors = pagy(@category.users, items: 18)
  end
end

app/views/admins/categories/_form.html.erb
<div class="field row mb-2 ms-5 mx-5">
  <%= form.label "Название", class: "col-sm-2 col-form-label" %>
  <div class="col-sm-10">
    <%= form.text_field :name, class: "form-control", placeholder: "Заголовок" %>
  </div>
</div>
<hr>
<div class="d-flex justify-content-end">
  <%= form.submit "Отправить", class: "btn text-white", style: "background: #1ec8c8;" %>
</div>

app/views/admins/categories/edit.html.erb
<div>
  <h3 class="mt-3">Изменить категорию</h3>
</div>
<hr>
<div>
  <%= form_with model: @category, url: admins_category_path, method: :put do |form| %>
    <%= render "admins/categories/form", form: form %>
  <% end %>
</div>

app/views/admins/categories/index.html.erb
<div>
  <h3 class="mt-3">Панель администратора: Категории</h3>
</div>
<hr>
<div class="d-flex justify-content-between align-items-center">
  <%= link_to "Создать категорию",
    new_admins_category_path,
    class: "btn text-white",
    style: "background: #1ec8c8;" %>
  <%= search_form_for @q, url: admins_categories_path do |f| %>
    <div class="input-group mb-3">
      <%= f.search_field :name_cont, class: "form-control" %>
      <%= f.submit t("buttons.search"), class: "btn text-white", style: "background: #1ec8c8;" %>
    </div>
  <% end %>
</div>
<hr>
<div>
  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <% %i[id name created_at updated_at].each do |attribute| %>
          <th scope="col"><%= sort_link(@q, attribute) %></th>
        <% end %>
        <th scope="col"><%= t("table.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <th><%= category.id %></th>
          <th><%= category.name %></th>
          <td><%= category.created_at %></td>
          <td><%= category.updated_at %></td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
              <%= link_to "Удалить", admins_category_path(category),
                  data: { turbo_method: :delete, turbo_confirm: "Вы точно хотите удалить эту категорию?" },
                  class: "btn btn-danger" %>
              <%= link_to "Изменить",
                  edit_admins_category_path(category),
                  class: "btn btn-success" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/admins/categories/new.html.erb
<div>
  <h3 class="mt-3">Создать категорию</h3>
</div>
<hr>
<div class="modal-body">
  <%= form_with model: @category, url: admins_categories_path, method: :post, data: { turbo: false } do |form| %>
    <%= render "admins/categories/form", form: form %>
  <% end %>
</div>