config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  namespace :admins do
    resources :patients
    resources :doctors
    resources :categories
  end

  resources :users
  resources :categories
  resources :appointments
  resources :recommendations

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :users

  validates :name, presence: true, uniqueness: true
end

app/controllers/admins/categories_controller.rb
# frozen_string_literal: true

class Admins::CategoriesController < Admins::AdminController
  before_action :set_category, only: %i[show update edit destroy]

  def index
    @q = Category.ransack(params[:q])
    @q.sorts = "created_at desc" if @q.sorts.empty?
    @pagy, @categories = pagy(@q.result, items: 10)
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = t("categories.create.flash.success")
    else
      flash[:alert] = t("categories.create.flash.alert")
    end

    redirect_to action: :index
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = t("categories.edit.flash.success")
    else
      flash[:alert] = t("categories.edit.flash.alert")
    end

    redirect_to action: :index
  end

  def destroy
    return unless @category.destroy

    flash[:notice] = t("categories.destroy.flash.success")
    redirect_to action: :index
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :users)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @q = Category.ransack(params[:q])
    @categories = @q.result
  end

  def show
    @category = Category.find(params[:id])
    @pagy, @category_doctors = pagy(@category.users, items: 18)
  end
end

app/views/categories/_category.html.erb
<li class="list-group-item border-0" id="<%= dom_id category %>">
  <%= link_to category_path(category),
      data: { turbo_frame: :show_category },
      class: "list-group-item-action d-flex pb-3 pt-3 px-2 align-items-center" do %>
    <%= bootstrap_icon "heart-pulse-fill", width: "30px", height: "30px" %>
    <h5 class="ms-2"><%= category.name %></h5>
  <%end%>
</li>

app/views/categories/_doctors.html.erb
<div class="row row-cols-1 row-cols-md-2">
  <% @category_doctors.each do |doctor| %>
    <div class="col mb-3">
      <div class="card">
        <div class="card-body d-flex justify-content-between align-items-center">
          <h5 class="ms-2 d-flex align-items-center">
            <span class="mx-2"><%= doctor.first_name %> <%= doctor.last_name %></span>
          </h5>
          <%= link_to "Записаться на приём",
              new_appointment_path(doctor_id: doctor),
              data: { turbo_frame: :modal },
              class: "btn text-white", style: "background: #1ec8c8;" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<hr>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/categories/index.html.erb
<div class="row h-100">
  <div id="categories" class="col-3 h-100">
    <div class="pt-3">
      <h3 class="text-center">Выберите категорию</h3>
    </div>
    <hr>
    <div>
      <%= search_form_for @q, url: categories_path do |f| %>
        <div class="input-group mb-3">
          <%= f.search_field :name_cont, class: "form-control" %>
          <%= f.submit t("buttons.search"), class: "btn text-white", style: "background: #1ec8c8;" %>
        </div>
      <% end %>
    </div>
    <hr>
    <div class="category-list">
      <ul class="list-group" id="categories_search">
        <% @categories.each do |category| %>
          <%= render category %>
        <% end %>
      </ul>
    </div>
  </div>
  <%= turbo_frame_tag :show_category, class: "col border-start" %>
  <%= turbo_frame_tag :modal %>
</div>

app/views/categories/show.html.erb
<%= turbo_frame_tag :show_category do %>
   <div class="pt-3">
    <h3>Список врачей категории <%= @category.name %></h3>
  </div>
  <hr/>
  <div id="doctors" class="doctors-cards-block">
    <%= render "categories/doctors" %>
  </div>
<% end %>